In [1]:
# Mengimpor perpustakaan yang diperlukan
import pandas as pd               
import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
%matplotlib inline     
sns.set(color_codes=True)

In [2]:
# Memuat file CSV ke dalam kerangka data pandas.
df = pd.read_csv(r"C:\Users\AKU\tugas_prog\pak rolly\ai\solo presentasi\cars.csv")
df.head(5)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945.0,33337.0,3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820.0,21761.0,2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,26990.0,24647.0,2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,33195.0,30299.0,3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755.0,39014.0,3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [ ]:
# Menghapus fitur yang tidak relevan
df = df.drop(['Model','DriveTrain','Invoice', 'Origin', 'Type'], axis=1)
df.head(5)

In [ ]:
# Untuk mengidentifikasi jenis data
df.info()

In [ ]:
# Mendapatkan jumlah instance dan fitur
df.shape

In [ ]:
# Mendapatkan dimensi bingkai data
df.ndim

In [ ]:
df = df.drop_duplicates(subset='MSRP', keep='first')
df.count()

# Ini adalah hal yang berguna untuk dilakukan pada kumpulan data karena seringkali mungkin ada duplikat atau redundansi data,
# dalam kumpulan data, untuk menghapus ini saya menggunakan MSRP sebagai referensi sehingga tidak boleh 
# ada lebih dari dua harga MSRP yang sama dari mobil, itu menunjukkan bahwa hanya sedikit data yang berlebihan 
# karena harga mobil tidak pernah bisa menandingi dengan sangat akurat. Jadi sebelum dihapus duplikatnya ada 428 baris 
# dan setelah dihapus ada 410 artinya ada 18 data duplikat.